import React, { useState } from 'react';
import { getTranslation } from '../../i18n/translations';
import { CheckCircle2, FileText, Calendar, Building2, PhoneCall, Download, Sparkles, ArrowLeft, ExternalLink } from 'lucide-react';
import confetti from 'canvas-confetti';

export default function ActStep({
  analysisData,
  onOpenDPR,
  onBack,
  currentLang
}) {
  const t = (key) => getTranslation(currentLang, key);

  const [checkedDocs, setCheckedDocs] = useState({
    'aadhaar': true,
    'pan': true,
    'land': false,
    'dpr': true,
    'quotes': false,
    'caste': true,
    'noc': false
  });

  const toggleDoc = (id) => {
    setCheckedDocs(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const handleLaunchDPR = () => {
    confetti({
      particleCount: 80,
      spread: 70,
      origin: { y: 0.6 }
    });
    onOpenDPR();
  };

  const { roadmap, schemes, profile } = analysisData;
  const bestScheme = schemes.bestScheme;

  const mandatoryDocs = [
    { id: 'aadhaar', name: 'Aadhaar Card (Linked with Mobile)', mandatory: true },
    { id: 'pan', name: 'PAN Card of Entrepreneur / Firm', mandatory: true },
    { id: 'dpr', name: 'Bankable Detailed Project Report (Generated by RuralBiz AI)', mandatory: true },
    { id: 'quotes', name: 'Machinery & Equipment Quotations with GST numbers', mandatory: true },
    { id: 'land', name: 'Land Title Records (7/12, RoR) or 5-Year Registered Lease Agreement', mandatory: true },
    { id: 'caste', name: 'Special Category / Caste Certificate (For 35% Subsidy)', mandatory: profile.demographics.category !== 'General' },
    { id: 'noc', name: 'Gram Panchayat NOC for commercial electricity connection', mandatory: false }
  ];

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Celebration / Final Step Banner */}
      <div className="bg-gradient-to-r from-emerald-600 via-rural to-emerald-800 rounded-2xl p-6 sm:p-8 text-white shadow-md flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="space-y-2 text-center md:text-left">
          <div className="inline-flex items-center gap-2 bg-amber-400 text-rural-dark px-2.5 py-0.5 rounded-full text-xs font-black uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5" />
            Project Structure Complete
          </div>
          <h2 className="text-2xl sm:text-3xl font-black tracking-tight">
            Your {profile.businessName} is Ready for Bank Submission!
          </h2>
          <p className="text-xs sm:text-sm text-emerald-100 max-w-xl">
            Download your official Bankable Detailed Project Report (DPR) formatted according to RBI & KVIC appraisal standards.
          </p>
        </div>

        <button
          type="button"
          onClick={handleLaunchDPR}
          className="flex-shrink-0 flex items-center gap-3 bg-amber-400 hover:bg-amber-300 text-slate-900 font-extrabold text-sm sm:text-base px-6 py-4 rounded-xl shadow-lg hover:shadow-xl transition-all hover:scale-105 active:scale-95"
        >
          <FileText className="w-5 h-5 text-slate-900" />
          <span>Generate Bankable DPR</span>
        </button>
      </div>

      {/* 4-Phase Roadmap Timeline */}
      <div className="bg-white rounded-2xl p-6 sm:p-8 border border-slate-200 shadow-sm space-y-6">
        <div className="flex items-center gap-3 border-b border-slate-100 pb-4">
          <div className="w-9 h-9 rounded-xl bg-purple-50 text-purple-700 flex items-center justify-center font-bold">
            <Calendar className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900">4-Phase Implementation Milestone Roadmap</h3>
            <p className="text-xs text-slate-500">Day-by-day practical operational playbook for rural entrepreneurs</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {roadmap.map((milestone, idx) => (
            <div
              key={idx}
              className="p-5 rounded-2xl border border-slate-200 bg-slate-50/50 hover:bg-white hover:border-rural/40 hover:shadow-sm transition-all space-y-3"
            >
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-rural-pale text-rural-dark border border-rural-border">
                  {milestone.duration}
                </span>
                <span className="text-[11px] font-semibold text-slate-400">
                  {milestone.status}
                </span>
              </div>

              <h4 className="font-bold text-sm text-slate-900 leading-snug">
                {milestone.phase}
              </h4>

              <ul className="space-y-2 text-xs text-slate-600">
                {milestone.tasks.map((task, tIdx) => (
                  <li key={tIdx} className="flex items-start gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-rural flex-shrink-0 mt-0.5" />
                    <span>{task}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>

      {/* Mandatory Documents Checklist & DIC / Bank Contacts */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Left: Checklist */}
        <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div>
              <h4 className="text-sm font-bold text-slate-900">Mandatory Application Checklist</h4>
              <p className="text-[11px] text-slate-500">Carry these documents to your DIC or Bank Branch</p>
            </div>
            <span className="text-xs font-bold text-rural bg-rural-pale px-2 py-0.5 rounded">
              {Object.values(checkedDocs).filter(Boolean).length} / {mandatoryDocs.length} Ready
            </span>
          </div>

          <div className="space-y-2.5">
            {mandatoryDocs.map((doc) => {
              const isChecked = checkedDocs[doc.id];
              return (
                <div
                  key={doc.id}
                  onClick={() => toggleDoc(doc.id)}
                  className={`p-3 rounded-xl border cursor-pointer flex items-center justify-between transition-all ${
                    isChecked
                      ? 'bg-emerald-50/70 border-emerald-300 text-slate-900'
                      : 'bg-slate-50 border-slate-200 text-slate-600 hover:bg-slate-100'
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      checked={isChecked}
                      onChange={() => {}}
                      className="w-4 h-4 text-rural rounded accent-rural cursor-pointer"
                    />
                    <span className="text-xs font-semibold">{doc.name}</span>
                  </div>
                  {doc.mandatory && (
                    <span className="text-[9px] font-bold text-red-600 bg-red-50 px-1.5 py-0.5 rounded border border-red-200 flex-shrink-0">
                      Required
                    </span>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Right: DIC & Scheme Portal Hub */}
        <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm space-y-4">
          <div className="flex items-center gap-3 border-b border-slate-100 pb-3">
            <div className="w-8 h-8 rounded-lg bg-blue-100 text-khadi flex items-center justify-center font-bold">
              <Building2 className="w-4 h-4" />
            </div>
            <div>
              <h4 className="text-sm font-bold text-slate-900">Nodal Agency & Bank Mitra Support</h4>
              <p className="text-[11px] text-slate-500">Official nodal office for {profile.district} District</p>
            </div>
          </div>

          <div className="p-4 bg-blue-50/60 border border-blue-200 rounded-xl space-y-2 text-xs">
            <div className="font-bold text-slate-900">District Industries Centre (DIC) {profile.district}</div>
            <p className="text-slate-600">Nodal Officer for PMEGP Task Force clearance & Udyam facilitation.</p>
            <div className="flex items-center gap-2 text-khadi font-semibold pt-1">
              <PhoneCall className="w-3.5 h-3.5" />
              <span>Helpline: 1800-180-6763 (Toll Free)</span>
            </div>
          </div>

          <div className="space-y-2 pt-2">
            <span className="text-xs font-bold text-slate-700 block">Direct Government Portals:</span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              <a
                href="https://www.kviconline.gov.in/pmegpeportal/"
                target="_blank"
                rel="noreferrer"
                className="flex items-center justify-between p-2.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-800 hover:border-rural hover:text-rural transition-colors"
              >
                <span>PMEGP e-Portal</span>
                <ExternalLink className="w-3.5 h-3.5 opacity-50" />
              </a>
              <a
                href="https://udyamregistration.gov.in/"
                target="_blank"
                rel="noreferrer"
                className="flex items-center justify-between p-2.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-800 hover:border-rural hover:text-rural transition-colors"
              >
                <span>Udyam Registration</span>
                <ExternalLink className="w-3.5 h-3.5 opacity-50" />
              </a>
            </div>
          </div>

          <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-900">
            <strong>CSC / VLE Assist:</strong> You can take your printed RuralBiz AI DPR to any nearest Common Service Centre (CSC) for instant online upload.
          </div>
        </div>
      </div>

      {/* Navigation Footer */}
      <div className="flex items-center justify-between pt-4">
        <button
          type="button"
          onClick={onBack}
          className="flex items-center gap-2 text-xs font-bold text-slate-600 hover:text-slate-900 px-4 py-2.5 rounded-xl border border-slate-300 hover:bg-slate-100 transition-all"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>{t('backButton')}</span>
        </button>

        <button
          type="button"
          onClick={handleLaunchDPR}
          className="flex items-center gap-2 bg-gradient-to-r from-solar to-amber-600 hover:from-solar-dark hover:to-amber-700 text-white font-bold text-sm px-6 py-3 rounded-xl shadow-md hover:shadow-lg transition-all hover:scale-102"
        >
          <FileText className="w-4 h-4" />
          <span>{t('generateDprButton')}</span>
        </button>
      </div>
    </div>
  );
}
